# src/main/resources/application.yml
spring:
  application:
    name: gcp-demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.example.gcpdemo: INFO